export const NOTIFICATION_TRIGGERS = {
  TASK_CREATED: "task_created",
  TASK_ASSIGNED: "task_assigned",
  TASK_UNASSIGNED: "task_unassigned",
  TASK_STATUS_CHANGED: "task_status_changed",
  TASK_PRIORITY_CHANGED: "task_priority_changed",
  TASK_DUE_DATE_CHANGED: "task_due_date_changed",
  TASK_COMPLETED: "task_completed",
  TASK_MOVED: "task_moved",
  TASK_DELETED: "task_deleted",
  ATTACHMENT_ADDED: "attachment_added",
  COMMENT_ADDED: "comment_added",
  COMMENT_REPLY: "comment_reply",
  MENTION_COMMENT: "mention_comment",
  MENTION_DESCRIPTION: "mention_description",
  COMMENT_RESOLVED: "comment_resolved",
  DUE_DATE_REMINDER_1DAY: "due_date_reminder_1day",
  DUE_DATE_TODAY: "due_date_today",
  TASK_OVERDUE: "task_overdue",
  WORKSPACE_INVITED: "workspace_invited",
  INVITE_ACCEPTED: "invite_accepted",
  SPACE_ADDED: "space_added",
  SPACE_REMOVED: "space_removed",
  SPACE_ARCHIVED: "space_archived",
  SPACE_RESTORED: "space_restored",
  ROLE_CHANGED: "role_changed",
  SPACE_PERMISSION_CHANGED: "space_permission_changed",
  WORKSPACE_REMOVED: "workspace_removed",
  SPRINT_STARTED: "sprint_started",
  SPRINT_ENDING_SOON: "sprint_ending_soon",
  SPRINT_CLOSED: "sprint_closed",
  SPRINT_AUTO_CREATED: "sprint_auto_created",
} as const;

export type NotificationTriggerType = (typeof NOTIFICATION_TRIGGERS)[keyof typeof NOTIFICATION_TRIGGERS];
